### ISSUE TITLE
Refactor initiative carousel to show more initiatives

### ISSUE THREAD

**Issue by georgimld** [openkfw/innoverse#13]
On the landing page, change the carousel that currently shows the initiatives to either:
- Cards are shown vertically on the landing page
- New initiatives pages that show all the initiatives.

Notes: 

* Change structure to a 3 or 4-column lazy load section. (No horizontal slider)
* Add filter options, especially an instant search filter

**Comment by zararsiz** [comment]
UI / Figma file: 

https://www.figma.com/design/N21dWppxv7VJCpdfUPgCfK/KfW-%E2%80%93%C2%A0DEV-Handoff-(All-Sprints)?node-id=4096-22559&m=dev

**Comment by georgimld** [comment]
Will be replaced by issue #56
