### ISSUE TITLE
Close Input field when clicking on "antworten" again

### ISSUE THREAD

**Issue by georgimld** [openkfw/innoverse#45]
When the input field in the "Antworten" view is open, i want to be able to close it back again when clicking on the "Antworten" button again
<img width="823" alt="image" src="https://github.com/user-attachments/assets/ee79a101-93b3-47d8-8143-343c71329212">

**Comment by georgimld** [comment]
@zararsiz do you agree?

**Comment by zararsiz** [comment]
Yes! After clicking "Send," the input field should disappear, and the new message should be placed on its specified location.

**Comment by zararsiz** [comment]
Oh wait, I think I misunderstood. If someone clicks the reply button but then decides not to reply anymore, there is a "Cancel" button next to the reply button. See the attachment.
![Screenshot 2024-09-30 at 13 41 36](https://github.com/user-attachments/assets/fe466b1f-379e-48e7-b6b9-5aaf89a0951b)

Figma: https://www.figma.com/design/N21dWppxv7VJCpdfUPgCfK/KfW-InnoVerse-%E2%AD%90%EF%B8%8F-%E2%80%93%C2%A0DEV-Handoff-(All-Sprints)?node-id=4051-9075&t=Ff6tKfTkpltjYfAz-1
