### ISSUE TITLE
Upgrade Emoji-Version @emoji-mart/data

### ISSUE THREAD

**Issue by maurices3001** [openkfw/innoverse#48]

**Comment by simonhrmo** [comment]
hello @maurices3001 :)

Could you please provide more details on the specific version we're aiming for? We should be able to handle configuration options similar to what's shown here: [@emoji-mart/data](https://missiveapp.com/open/emoji-mart).

**Comment by maurices3001** [comment]
> hello @maurices3001 :)
> 
> Could you please provide more details on the specific version we're aiming for? We should be able to handle configuration options similar to what's shown here: [@emoji-mart/data](https://missiveapp.com/open/emoji-mart).

hey @simonhrmo 
Is it possible to adopt the attached configuration settings?
![Screenshot 2024-09-24 160213](https://github.com/user-attachments/assets/d52e5d54-c738-4250-a7bc-bc6f5d6c20ab)
